### ISSUE TITLE
Inferring and analytically marginalizing over noise standard deviation

### ISSUE THREAD

**Issue by jeromefung** [manoharan-lab/holopy#272] opened 2019-06-18 16:53 UTC
As currently formulated, the posterior that is sampled when doing Bayesian inference involving holograms assumes a fixed, known standard deviation \sigma for the noise on each pixel. In practice, the actual \sigma is seldom known but is estimated from the variance in the hologram being analyzed.

It is possible to treat \sigma as a parameter to be inferred and then to marginalize over it analytically (e.g., integrate Eq. 12 in [Dimiduk & Manoharan, 2016](https://manoharan.seas.harvard.edu/files/manoharan/files/bayesian-holography.pdf) with respect to \sigma from 0 to infinity, which would assume a uniform prior on \sigma). The resulting posterior would have a different form than the one now used (it would be proportional to a power of the unweighted chi-squared). If there is interest I can write up the details.

Is there a reason (numerical or otherwise) why this would be a bad idea, or is this a feature we should consider adding?

**Comment by vnmanoharan** [comment] 2019-06-19 18:41
I think this would be a useful feature.  You would probably want to use a Jeffreys prior if \sigma can vary over more than one order of magnitude. In that case the marginalization integral will depend on the limits of the prior.  It may be better to allow the user to add \sigma as a parameter, assign it an arbitrary prior, and then sample over the joint posterior (including sigma).  Then the user can easily marginalize numerically.

We would probably have to target this for 3.4 or later.

**Comment by briandleahy** [comment] 2019-07-02 13:56
Thanks for the question. My impression is that sampling over the noise level isn't currently supported in holopy, and I'm a little confused as to why this isn't implemented, because running MCMC with a ```__lnsigma``` parameter is supported by ```emcee``` and it works fine (@ralex0 and I have been doing it quite a bit, but by working around holopy). I was talking to @barkls about why this wasn't supported and I believe he mentioned that there is no good reason why this doesn't work. 

@jeromefung -- you asked

> Is there a reason (numerical or otherwise) why this would be a bad idea, or is this a feature we should consider adding?

As I mentioned above, there is no numerical reason why this is a bad idea. But just a heads-up if you are actually trying this, in my previous experience it's usually best to only start sampling over sigma once the other parameters are fairly close to the actual values. (Otherwise the estimated ```sigma``` gets huge, then the other parameters drift a lot, and it takes a while for the parameters to return to their correct levels.)

**Comment by barkls** [comment] 2019-07-02 16:56
I've taken a stab at solving this since I thought it would be trivially easy.

However, I ran into a slight hiccup. Specifically,  the name `noise_sd` is problematic as a paramter because it has an underscore in it, and holopy tries to combine parameters with underscores into dictionaries (e.g. `{'alpha_red':0.8, 'alpha_green':0.9}`). I see three possible solutions: 
1) rename `noise_sd` throughout holopy to something without an underscore. I don't have a suggestion for a new name.
2) keep `noise_sd` in the API but rename the parameter as simply `noise`. This could be needlessly confusing.
3) stop using underscores when parsing parameter names, and switch to a colon or something instead. This will break backwards-compatibility and file-loading of two-colour holograms specifically, but I don't know if anyone else was actually using this feature.

**Comment by jeromefung** [comment] 2019-07-02 17:13
Thanks for looking into this. The API preferences of the people regularly using holopy should outweigh mine, but my inclination is to avoid unnecessarily breaking backwards compatibility. Would option #2 with a name like `noisestd` be less confusing than `noise`?

**Comment by barkls** [comment] 2019-07-11 16:25
I ended up going with option 3 in #279 because it's completely reasonable for developers to have underscores in their variable names and we shouldn't interfere with that, so I think it's the most future-proof (although maybe slightly breaking now).

I haven't tried inferring a noise level yet but I have confirmed the code on my branch runs. It might be tricky to define an appropriate prior, but you'll have to try it out.

Good luck!

**Closed by barkls** 2019-07-11 16:25 UTC
Labels: enhancement, question
