### ISSUE TITLE
emcee 3.0 introduces API changes

### ISSUE THREAD

**Issue by barkls** [manoharan-lab/holopy#288] opened 2019-08-06 17:58 UTC
The upcoming 3.0 release of emcee has changed its user interface in a few different ways. We will need to make sure HoloPy adapts to the new interface once it is officially released on conda-forge and pypi. For an example of a breaking change, see #285.

**Comment by barkls** [comment] 2019-10-15 13:44
Note that `conda install -c conda-forge emcee` now installs version 3, so we should specify HoloPy compatibility with emcee < 3.0 until we switch over.

**Comment by ralex0** [comment] 2019-12-08 00:44
@barkls, per your suggestion, I tested the code in #285 that @NRanta posted. This minimal version runs without issue on our current 3.3 branch.
```python
import holopy as hp
from holopy.scattering import Sphere, calc_holo
from holopy.inference import AlphaModel, TemperedStrategy
from holopy.fitting import Parameter as par

if __name__ == '__main__':
    sph = hp.scattering.Sphere(n=1.59, r=9, center=(30, 30, 40)) 
    detector = hp.detector_grid(shape=600, spacing=.1) 
    medium_index = 1.33 
    illum_wavelen = 0.660 
    illum_polarization = (1,0) 

    data_holo = calc_holo(detector, sph, medium_index, 
                          illum_wavelen, illum_polarization)

    n = par(guess=1.65, limit=[1.5, 1.7])
    rad = 9
    x_loc = 30
    y_loc = 30
    z_loc = 40
    center_loc = (x_loc, y_loc, z_loc)

    s = Sphere(n=n, r=rad, center=center_loc)

    noise_sd = data_holo.std()
    model = AlphaModel(s,par(.6, [.1,1]), noise_sd)
    strat = TemperedStrategy()
    strat = TemperedStrategy(nwalkers=4, stages=2, npixels=100)

    hp.save('test', result.MAP)
```
Our current tests cover this. My current emcee version is 3.0.2

I'm closing this because there is no failing use case.

**Comment by briandleahy** [comment] 2019-12-08 14:53
Thanks @ralex0 . Do the tests pass with `emcee` v 3.x? I remember that 2 tests were failing with emcee 3.x, is that also fixed?

**Comment by ralex0** [comment] 2019-12-08 21:16
@briandleahy see #308. I fixed all the tests in test_emcee

**Comment by barkls** [comment] 2019-12-18 21:54
Our code is not incompatible with earlier versions of emcee. This is problematic since we removed emcee as a dependency, but now we can't enforce any version control. Running a MCMC calculation with the older version of emcee gives an opaque AttributeError. Ideally we could specify `emcee>=3.0` as an optional dependency that is enforced only if it is already installed but I don't think that's possible with conda. We could use a try-except to check against both versions of the emcee API and raise a warning. Does anyone have a better solution @ralex0 @briandleahy?

**Comment by briandleahy** [comment] 2019-12-18 22:08
We could try requiring emcee > 3.0 in the `extras_require` in setuptools, cf. https://setuptools.readthedocs.io/en/latest/setuptools.html

**Comment by ralex0** [comment] 2019-12-19 01:13
For holopy-feedstock, we can specify `emcee>=3.0` in [recipe/meta.yaml](https://github.com/conda-forge/holopy-feedstock/blob/master/recipe/meta.yaml) and do the same in [/.travis.yml](https://github.com/manoharan-lab/holopy/blob/3.3-rebase/.travis.yml) in this repo.

I don't think we should support outdated versions of emcee. Let's just use the `extras_require` kwarg in setup.py as @briandleahy suggests.

If emcee is really not required, then we should just remove it from [/.travis.yml](https://github.com/manoharan-lab/holopy/blob/3.3-rebase/.travis.yml), right? Then Travis won't run the MCMC tests, but that's the cost of removing the requirement.

**Comment by vnmanoharan** [comment] 2019-12-19 14:21
Note that the [parallel tempering sampler has been removed from emcee 3.0](https://github.com/dfm/emcee/issues/236).  So if you have code that relies on parallel tempering, it will be broken in HoloPy 3.3 with the `emcee>=3.0` dependency.

**Comment by barkls** [comment] 2019-12-19 14:50
Thanks for the suggestions!

`extras_require` will solve the problem for anyone building from source, but not those using the conda distribution. Problem case is if someone has emcee 2.2.1 installed (e.g. from an earlier version of holopy) and then does `conda install holopy`. Now holopy MCMC calculations will fail, but without giving any indication that there's a compatibility issue (it raises an AttributeError). 

@ralex0 suggests making emcee a dependency of holopy for the conda build only, which would work. How do we feel about having different dependencies across different distributions? 

I don't think we should remove emcee from Travis since we rely on it to run all the tests (although our current approach to DDA matches what you suggest). We could automate 2 travis builds, one to check minimal dependencies and one to run all tests. We'd want to rework the tests so they skip instead of failing if emcee (and other dependencies) is absent. Personally I don't think this is worth the effort since it's not clear to me what the benefit is.

Parallel tempering code hasn't made it into HoloPy yet so there are not problems there.

**Comment by vnmanoharan** [comment] 2019-12-19 15:01
I wasn't talking about code in holopy.  @ralex0 has PT code that was used to generate results for the mie-lens paper.  He (and anyone else using parallel tempering) should be aware that their code will not work with holopy 3.3.

**Comment by barkls** [comment] 2019-12-19 21:33
`extras_require` looks like it's for optional features that are identified by name as dependencies for another project, which isn't quite our situation.

[This stackoverflow thread](https://stackoverflow.com/questions/57938558/can-i-declare-incompatible-python-dependencies) makes it sound like what we want to do isn't possible. 

Any other ideas? Am I missing something? Should we just handle both for now?

Since parallel tempering isn't built into HoloPy, anyone using it would have to work around HoloPy's inference tools anyway (like Ron did), so this change wouldn't affect their code. It could be a problem if somebody out there has code that uses both parallel tempering (emcee 2.2) and HoloPy MCMC (emcee 3.0) at once.  I'll add a line to the docs about the migration so hopefully that makes it more clear.

**Comment by briandleahy** [comment] 2019-12-19 21:49
Hmmm... my impression (from [these docs](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies)) is that `extras_require` is for optional features that are identified by name, but that are part of our package. That seems to be the case here. For instance, if someone wants to do inference with emcee, that requires `emcee>3.0`. If someone wants to do inference with CMA-ES, that requires `cma`. That seems like the use case for me. I'd prefer using `extras_require`, but I'm also fine with just putting the dependencies as mandatory (although it's a little more heavy-handed than it needs to be).

A line to the docs would be great though!

I'm happy to do these things if you want, or I'm happy to let you do it. Just let me know.

And regarding the parallel tempering -- I agree that we should not worry about losing PT support in holopy, since @ralex0 and I did the inference without using holopy's inference package. My dream is  that ideally, in the future, we could make holopy's inference api to be agnostic of the particular inference strategy used, which would help with "dependency hells" like this.

**Comment by barkls** [comment] 2019-12-19 21:57
My understanding from reading those docs and playing around with it is that we can specify `emcee>=3.0.0` in `extras_require`, but that won't be enforced unless something else specifically has that HoloPy extra as a requirement. 

For example, we could define a feature of HoloPy "MCMC" that includes the emcee interface part of HoloPy and requires emcee>=3.0.0. This requirement isn't enforced when installing HoloPy - you can have emcee 3.0.0, 2.2.1, or none at all. If some other package wants to build on HoloPy's EmceeStrategy, it can require `HoloPy[MCMC]` as a dependency, which will then enforce `emcee>=3.0.0`.

We could maybe design some sort of package hierarchy to make this work but I don't think that's the right solution here. Let me know if you're still interpreting things differently!

**Comment by vnmanoharan** [comment] 2019-12-19 22:11
Re: PT support.  It's not so simple.  If you add emcee>3.0 as a dependency to the conda-forge build, installing holopy 3.3 will update your emcee to the version without parallel tempering.  Then you can't use PTSampler with holopy 3.3 in the same environment.  There is a fork of PTSampler into a separate package, but it's not as easy to use as the PTSampler in emcee 2.2.  So I am against adding emcee>3.0 as a dependency.

**Comment by barkls** [comment] 2019-12-19 22:15
Do you think we should support both emcee 2.2 and 3.0 for now?

**Comment by vnmanoharan** [comment] 2019-12-19 22:59
A major new feature of holopy 3.3 is the mielens model.  As discussed in the paper, inferring certain parameters using the mielens model requires parallel tempering.  If we require emcee>3.0, we eliminate one of the tools needed to use the new feature.  Worse, anyone who wants to reproduce the results in the paper would have to jump through hoops to do so, since the results were obtained with emcee 2.2.

I don't think we have a choice.

**Comment by briandleahy** [comment] 2019-12-19 23:18
I think @vnmanoharan has a good point regarding parallel tempering and the mielens model; we should allow a user to use 3.3 with parallel tempering emcee.

I still do think that making `emcee` an optional dependency would solve this. For now we could leave HoloPy's `EmceeStrategy` compatible only with emcee 3.x. Then it is possible for a user to use parallel tempering with 3.3, although they would need to implement their own inference strategy (as @ralex0  and I did).

In my opinion, on a longer time scale `holopy` should not be about inference, as @ralex0 and I have said many times in hushed tones. I think we should ideally just provide a way to calculate (likelihoods, priors, posteriors, and residuals), and the user should then use that to do the inference on their own. This would avoid binding us to specific emcee or cma-es dependencies, and we wouldn't need to update `holopy` every time `emcee`, `cma`, or `scipy` change their interface. But this is another discussion for another time.

**Comment by barkls** [comment] 2019-12-20 17:42
It sounds like we need to support the following two cases:

> User 1 has holopy 3.2 and emcee 2.2 installed. They upgrade HoloPy to 3.3 with conda. They don't care which emcee version they have as long as they can do MCMC calculations within HoloPy.

>User 2 wants to use holopy 3.3 for mielens, and they want to sue parallel tempering so they need emcee 2.2. They don't care about doing MCMC calculations within HoloPy.

The 3.0.0 release satisfies both of these users **as long as user 2 doesn't install holopy with conda**. This might be acceptable because the mielens code doesn't need to be compiled. We could add some documentation about this caveat if others feel this is an acceptable option.

If user 2 insists on installing holopy with conda, their parallel tempering will break since the conda distribution requires emcee>=3.0.0. If we remove that dependency, user 1's emcee will no longer upgrade with holopy and their built-in holopy MCMC won't work. The only solution I see is to remove the dependency and support both versions of emcee within HoloPy's MCMC framework (or support only emcee<3.0.0 and include that as a dependency, but that seems like a bad idea).

I've submitted a PR #316 that restores compatibility with earlier versions of emcee. It's messy, but I think it's the only way to resolve this dilemma unless user 2 can be convinced not to use conda. I'd appreciate a code review @briandleahy, but I'll merge in my PR and release it as HoloPy 3.3.1 by end of day if I don't hear anything.

**Comment by briandleahy** [comment] 2019-12-20 17:49
I agree that it's messy, but I think that that is a good stop-gap and it is certainly an improvement over the current status. The best is the enemy of the good, and I think what you submitted is good. We can talk about better long-term solutions later.

I left a quick code review; see #316 .

Thanks for taking care of this @barkls .

**Closed** 2021-02-25 21:31 UTC
